language: node_js
node_js:
    - "lts/*"

addons:
    apt:
        packages:
            - gyp

services:
    - postgresql
    - redis-server

cache:
    npm: true

before_script:
    - npm install -g npm
    - npm i -g bunyan mocha node-gyp tslint typings typescript
    - npm config set spin false
    - psql -c 'create database travis_ci_test;' -U postgres

env:
    global:
        - RDBMS_URI='postgres://postgres@localhost/travis_ci_test'

install:
    - typings install
    - npm install

script:
    - npm test
