name: TypeScript build

on: [push]

jobs:
  build-and-compile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install dependencies and compile
        run: |
          npm i -g npm && \
          npm i -g typescript typings && \
          typings i && \
          npm ci && \
          tsc
